#ifndef __BANK0_SPEECH_DEFINES_H__
#define __BANK0_SPEECH_DEFINES_H__

enum BANK0_SPEECH_ENUMS
{
SPEECH_CH1_BREAD = 0x0,
SPEECH_CH1_HELMET = 0x19,
SPEECH_CH1_I_LIKE_YOU = 0x2c,
SPEECH_CH1_SPNGEBOB_ARRRG = 0x4f,
SPEECH_CH1_SPONGEBOB_VACATION = 0x72,
SPEECH_CH1_TAKE_THAT_YOU = 0x89,
SPEECH_CH1_YIPPE = 0xb0,
SPEECH_SPONGEBOB_ANNOYING_LAUGH = 0xc4,
SPEECH_SPONGEBOB_BREATHING = 0xd1,
SPEECH_SPONGEBOB_BUBBLEBLOW = 0xdf,
SPEECH_SPONGEBOB_BURP = 0xea,
SPEECH_SPONGEBOB_COUGH_COUGH = 0xf4,
SPEECH_SPONGEBOB_HIYA = 0x101,
SPEECH_SPONGEBOB_IM_READY = 0x10b,
SPEECH_SPONGEBOB_I_LOVE_BIKIBI_BOTTOM = 0x119,
SPEECH_SPONGEBOB_I_NEED_WATER = 0x126,
SPEECH_SPONGEBOB_LET_ME_JUST_GRAB = 0x131,
SPEECH_SPONGEBOB_OPPPS_PANTS = 0x140,
SPEECH_SPONGEBOB_OUCH = 0x14f,
SPEECH_SPONGEBOB_YIKES = 0x157,
SPEECH_SPONGEBOB_YOU_CANT_FOOL_ME = 0x160,
};
#endif
