//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MULTIBAR                    103
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR                     128
#define IDR_MAPEDITYPE                  129
#define IDD_LAYER_LIST                  147
#define IDI_PAINT                       152
#define IDI_SELECT                      153
#define IDD_RESIZE                      167
#define IDD_NEWMAP                      169
#define IDD_ADDLAYER                    172
#define IDD_TILEBANK                    173
#define IDD_TOOLBAR                     174
#define IDD_LAYER_SHADE                 175
#define IDD_LAYER_COLLISION             177
#define IDD_ELEMLIST                    178
#define IDD_LAYER_ACTOR                 179
#define IDD_LAYER_THING                 181
#define IDD_LAYER_THING_POS             182
#define IDD_LAYER_PLATFORM              183
#define IDD_LAYER_TRIGGER               184
#define IDD_LAYER_FX                    185
#define IDC_TOOLBAR_COMBO               1018
#define IDC_LAYERLIST_LIST              1019
#define IDD_TILEBANK_UPDATE             1029
#define IDD_TILEBANK_LOAD               1031
#define IDD_LAYERTILE_BTN_SELECT        1032
#define IDD_TILEBANK_DELETE             1033
#define IDD_LAYERTILE_BTN_PAINT         1034
#define IDC_MAPSIZE_WIDTH               1037
#define IDC_MAPSIZE_WIDTH_TEXT          1038
#define IDC_MAPSIZE_HEIGHT_TEXT         1039
#define IDC_MAPSIZE_HEIGHT              1040
#define IDC_MAPSIZE_WARNING             1041
#define IDC_LAYERLIST_ADD               1056
#define IDC_LAYERLIST_DELETE            1057
#define IDC_ADDLAYER_LIST               1058
#define IDC_LAYERSHADE_EDITR0           1060
#define IDC_LAYERSHADE_EDITG0           1061
#define IDC_LAYERSHADE_EDITB0           1062
#define IDC_LAYERSHADE_EDITR1           1064
#define IDC_LAYERSHADE_EDITG1           1065
#define IDC_LAYERSHADE_EDITB1           1066
#define IDC_LAYERSHADE_COUNTEDIT        1074
#define IDC_LAYERSHADE_COUNTTEXT        1075
#define IDC_SPIN2                       1076
#define IDC_LAYERCOLLISION_NORMAL       1078
#define IDD_ELEM_LIST                   1080
#define IDC_LAYERSHADE_EDITR2           1081
#define IDC_LAYERSHADE_EDITG2           1082
#define IDC_LAYERCOLLISION_DAMAGE       1082
#define IDC_LAYERSHADE_EDITB2           1083
#define IDC_LAYERCOLLISION_SLIPPERY     1083
#define IDC_LAYERCOLLISION_ELECTRIC     1084
#define IDC_LAYERCOLLISION_STICKY       1085
#define IDC_LAYERSHADE_TEXT7            1086
#define IDC_LAYERCOLLISION_WATER        1086
#define IDC_ACTOR_SPEED_TEXT            1086
#define IDC_LAYERSHADE_EDITR3           1087
#define IDC_LAYERCOLLISION_SOLID        1087
#define IDC_ACTOR_SPEED                 1087
#define IDC_LAYERSHADE_EDITG3           1088
#define IDC_LAYERCOLLISION_DEATH        1088
#define IDC_LAYERSHADE_EDITB3           1089
#define IDC_ACTOR_SPEED_SPIN            1092
#define IDC_ACTOR_PLAYER                1094
#define IDC_ACTOR_TURNRATE_TEXT         1097
#define IDC_ACTOR_TURNRATE              1098
#define IDC_ACTOR_TURNRATE_SPIN         1099
#define IDC_ACTOR_HEALTH_TEXT           1112
#define IDC_ACTOR_HEALTH                1113
#define IDC_ACTOR_HEALTH_SPIN           1114
#define IDC_ACTOR_ATTACK_TEXT           1115
#define IDC_ACTOR_ATTACK                1116
#define IDC_ACTOR_ATTACK_SPIN           1117
#define IDC_ACTOR_COLLISION             1118
#define IDC_DEF_THING_LIST              1124
#define IDC_THING_LIST                  1125
#define IDC_THING_GOTO                  1126
#define IDC_THING_DELETE                1127
#define IDC_THING_POS_LIST              1127
#define IDC_THING_POS_UP                1128
#define IDC_THING_POS_DOWN              1129
#define IDC_THING_POS_DELETE            1130
#define IDC_PLATFORM_SPEED              1131
#define IDC_PLATFORM_SPEED_TEXT         1132
#define IDC_PLATFORM_TURNRATE_TEXT      1133
#define IDC_PLATFORM_SPEED_SPIN         1134
#define IDC_PLATFORM_TURNRATE_SPIN      1135
#define IDC_PLATFORM_TURNRATE           1136
#define IDC_PLATFORM_COLLISION          1137
#define IDC_PLATFORM_MOVE_TYPE          1138
#define IDC_PLATFORM_TYPE               1139
#define IDC_TRIGGER_SIZE                1140
#define IDC_TRIGGER_WIDTH               1141
#define IDC_TRIGGER_HEIGHT              1142
#define IDC_TRIGGER_WIDTH_SPIN          1143
#define IDC_FX_SPEED_TEXT               1144
#define IDC_FX_SIZE_TEXT                1146
#define IDC_FX_WIDTH                    1147
#define IDC_FX_HEIGHT                   1148
#define IDC_FX_WIDTH_SPIN               1149
#define IDC_FX_TURNRATE_SPIN            1150
#define IDC_FX_SPEED                    1151
#define IDC_FX_SPEED_SPIN               1152
#define IDC_LAYERSHADE_BACKGFX0         1153
#define IDC_LAYERSHADE_SPIN0            1154
#define IDC_LAYERSHADE_BACKGFX1         1155
#define IDC_LAYERSHADE_MOVE0            1156
#define IDC_LAYERSHADE_SCALE0           1157
#define IDC_LAYERSHADE_COLOR0           1158
#define IDC_LAYERSHADE_SPIN1            1159
#define IDC_LAYERSHADE_MOVE1            1160
#define IDC_LAYERSHADE_SCALE1           1161
#define IDC_LAYERSHADE_TRANS0           1162
#define IDC_LAYERSHADE_COLOR1           1163
#define IDC_LAYERSHADE_TRANS1           1164
#define ID_TOOLBAR_TILEPALETTE          32774
#define ID_TOOLBAR_PARAMBAR             32783
#define ID_TOGGLE_SUBVIEW               32785
#define ID_MAP_TOGGLEGRID               32786
#define ID_TOGGLE_GRID                  32787
#define ID_MIRRORX                      32788
#define ID_MIRRORY                      32789
#define ID_ACTIVEBRUSH_LEFT             32790
#define ID_ACTIVEBRUSH_RIGHT            32791
#define ID_MAP_SETSIZE                  32792
#define ID_2D_3D_TOGGLE                 32794
#define ID_EXPORT                       32795
#define ID_ZOOM_IN                      32797
#define ID_ZOOM_OUT                     32798
#define ID_RESET_VIEW                   32799
#define ID_RENDER_TO_TGA                32800
#define ID_INDICATOR_CURSORXY           59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1163
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
