//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MULTIBAR                    103
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR                     128
#define IDR_MAPEDITYPE                  129
#define IDD_LAYER_LIST                  147
#define IDI_PAINT                       152
#define IDI_SELECT                      153
#define IDD_RESIZE                      167
#define IDD_NEWMAP                      169
#define IDD_ADDLAYER                    172
#define IDD_TILEBANK                    173
#define IDD_TOOLBAR                     174
#define IDD_LAYER_SHADE                 175
#define IDD_LAYER_COLLISION             177
#define IDD_ELEMLIST                    178
#define IDD_LAYER_ACTOR                 179
#define IDD_LAYER_THING                 181
#define IDD_LAYER_THING_POS             182
#define IDD_LAYER_PLATFORM              183
#define IDD_LAYER_TRIGGER               184
#define IDD_LAYER_FX                    185
#define IDD_LAYER_HAZARD                186
#define IDD_LAYER_RGB                   187
#define IDC_TOOLBAR_COMBO               1018
#define IDC_LAYERLIST_LIST              1019
#define IDD_TILEBANK_UPDATE             1029
#define IDD_TILEBANK_LOAD               1031
#define IDD_LAYERTILE_BTN_SELECT        1032
#define IDD_TILEBANK_DELETE             1033
#define IDD_LAYERTILE_BTN_PAINT         1034
#define IDC_MAPSIZE_WIDTH               1037
#define IDC_MAPSIZE_WIDTH_TEXT          1038
#define IDC_MAPSIZE_HEIGHT_TEXT         1039
#define IDC_MAPSIZE_HEIGHT              1040
#define IDC_MAPSIZE_WARNING             1041
#define IDC_LAYERLIST_ADD               1056
#define IDC_LAYERLIST_DELETE            1057
#define IDC_ADDLAYER_LIST               1058
#define IDC_LAYERSHADE_EDITR0           1060
#define IDC_LAYERSHADE_SHADER0          1060
#define IDC_LAYERSHADE_EDITG0           1061
#define IDC_LAYERSHADE_SHADEG0          1061
#define IDC_LAYERSHADE_EDITB0           1062
#define IDC_LAYERSHADE_SHADEB0          1062
#define IDC_LAYERSHADE_EDITR1           1064
#define IDC_LAYERSHADE_SHADER1          1064
#define IDC_LAYERSHADE_EDITG1           1065
#define IDC_LAYERSHADE_SHADEG1          1065
#define IDC_LAYERSHADE_EDITB1           1066
#define IDC_LAYERSHADE_SHADEB1          1066
#define IDC_LAYERSHADE_COUNTEDIT        1074
#define IDC_LAYERSHADE_SHADECOUNT       1074
#define IDC_LAYERSHADE_COUNTTEXT        1075
#define IDC_SPIN2                       1076
#define IDC_LAYERSHADE_SHADECOUNT_SPIN  1076
#define IDC_LAYERSHADE_COUNTTEXT2       1077
#define IDC_LAYERCOLLISION_NORMAL       1078
#define IDC_LAYERSHADE_POSTEXT          1078
#define IDC_LAYERSHADE_XYTEXT0          1079
#define IDD_ELEM_LIST                   1080
#define IDC_LAYERSHADE_XYTEXT1          1080
#define IDC_LAYERSHADE_EDITR2           1081
#define IDC_LAYERSHADE_SHADER2          1081
#define IDC_LAYERSHADE_EDITG2           1082
#define IDC_LAYERCOLLISION_DAMAGE       1082
#define IDC_LAYERSHADE_SHADEG2          1082
#define IDC_LAYERSHADE_EDITB2           1083
#define IDC_LAYERCOLLISION_SLIPPERY     1083
#define IDC_LAYERSHADE_SHADEB2          1083
#define IDC_LAYERCOLLISION_ELECTRIC     1084
#define IDC_LAYERSHADE_XYTEXT2          1084
#define IDC_LAYERCOLLISION_STICKY       1085
#define IDC_LAYERSHADE_XYTEXT3          1085
#define IDC_LAYERCOLLISION_DESTRUCT_WALL 1085
#define IDC_LAYERSHADE_TEXT7            1086
#define IDC_LAYERCOLLISION_WATER        1086
#define IDC_ACTOR_SPEED_TEXT            1086
#define IDC_LAYERCOLLISION_DEATH_LIQUID 1086
#define IDC_LAYERSHADE_EDITR3           1087
#define IDC_LAYERCOLLISION_SOLID        1087
#define IDC_ACTOR_SPEED                 1087
#define IDC_LAYERSHADE_SHADER3          1087
#define IDC_LAYERSHADE_EDITG3           1088
#define IDC_LAYERCOLLISION_DEATH        1088
#define IDC_LAYERSHADE_SHADEG3          1088
#define IDC_LAYERCOLLISION_DEATH_FALL   1088
#define IDC_LAYERSHADE_EDITB3           1089
#define IDC_LAYERSHADE_SHADEB3          1089
#define IDC_LAYERCOLLISION_DESTRUCTABLE 1089
#define IDC_LAYERCOLLISION_DESTRUCT_FLOOR 1089
#define IDC_LAYERSHADE_TRANSTEXT        1090
#define IDC_LAYERCOLLISION_MOVE_LEFT    1090
#define IDC_LAYERSHADE_GFXR0            1091
#define IDC_LAYERCOLLISION_MOVE_RIGHT   1091
#define IDC_ACTOR_SPEED_SPIN            1092
#define IDC_LAYERSHADE_GFXG0            1092
#define IDC_LAYERCOLLISION_DEATH_INSTANT 1092
#define IDC_LAYERSHADE_GFXB0            1093
#define IDC_LAYERCOLLISION_SOAK_UP      1093
#define IDC_ACTOR_PLAYER                1094
#define IDC_LAYERSHADE_GFXR1            1094
#define IDC_LAYERCOLLISION_SB_NOMOVE    1094
#define IDC_LAYERSHADE_GFXG1            1095
#define IDC_LAYERSHADE_GFXB1            1096
#define IDC_ACTOR_TURNRATE_TEXT         1097
#define IDC_ACTOR_TURNRATE              1098
#define IDC_ACTOR_TURNRATE_SPIN         1099
#define IDC_LAYERSHADE_GFXR2            1101
#define IDC_LAYERSHADE_GFXG2            1102
#define IDC_LAYERSHADE_GFXB2            1103
#define IDC_LAYERSHADE_GFXR3            1107
#define IDC_LAYERSHADE_GFXG3            1108
#define IDC_LAYERSHADE_GFXB3            1109
#define IDC_ACTOR_HEALTH_TEXT           1112
#define IDC_ACTOR_HEALTH                1113
#define IDC_ACTOR_HEALTH_SPIN           1114
#define IDC_ACTOR_ATTACK_TEXT           1115
#define IDC_ACTOR_ATTACK                1116
#define IDC_ACTOR_ATTACK_SPIN           1117
#define IDC_ACTOR_COLLISION             1118
#define IDC_DEF_THING_LIST              1124
#define IDC_THING_LIST                  1125
#define IDC_THING_GOTO                  1126
#define IDC_THING_DELETE                1127
#define IDC_THING_POS_LIST              1127
#define IDC_THING_POS_UP                1128
#define IDC_THING_POS_DOWN              1129
#define IDC_THING_POS_DELETE            1130
#define IDC_PLATFORM_SPEED              1131
#define IDC_PLATFORM_SPEED_TEXT         1132
#define IDC_PLATFORM_TURNRATE_TEXT      1133
#define IDC_PLATFORM_SPEED_SPIN         1134
#define IDC_PLATFORM_TURNRATE_SPIN      1135
#define IDC_PLATFORM_TURNRATE           1136
#define IDC_PLATFORM_COLLISION          1137
#define IDC_PLATFORM_MOVE_TYPE          1138
#define IDC_PLATFORM_TYPE               1139
#define IDC_TRIGGER_SIZE                1140
#define IDC_PLATFORM_PARAM0_TEXT        1140
#define IDC_TRIGGER_WIDTH               1141
#define IDC_PLATFORM_PARAM0             1141
#define IDC_TRIGGER_HEIGHT              1142
#define IDC_PLATFORM_PARAM_SPIN         1142
#define IDC_TRIGGER_WIDTH_SPIN          1143
#define IDC_FX_SPEED_TEXT               1144
#define IDC_TRIGGER_TARGET              1144
#define IDC_TRIGGER_TARGETX             1145
#define IDC_FX_SIZE_TEXT                1146
#define IDC_TRIGGER_TARGETX_SPIN        1146
#define IDC_FX_WIDTH                    1147
#define IDC_TRIGGER_TARGETY             1147
#define IDC_FX_HEIGHT                   1148
#define IDC_TRIGGER_TEXT_TARGET_WH      1148
#define IDC_FX_WIDTH_SPIN               1149
#define IDC_TRIGGER_TARGETW             1149
#define IDC_FX_HEIGHT_SPIN              1150
#define IDC_TRIGGER_TARGETW_SPIN        1150
#define IDC_FX_SPEED                    1151
#define IDC_TRIGGER_TARGETH             1151
#define IDC_FX_SPEED_SPIN               1152
#define IDC_TRIGGER_TEXT_VAL0           1152
#define IDC_TRIGGER_VAL0                1153
#define IDC_TRIGGER_VAL0_SPIN           1154
#define IDC_TRIGGER_HEIGHT_SPIN         1163
#define IDC_TRIGGER_TARGETY_SPIN        1164
#define IDC_TRIGGER_TARGETH_SPIN        1165
#define IDC_HAZARD_SPEED_TEXT           1169
#define IDC_HAZARD_TURNRATE_TEXT        1170
#define IDC_HAZARD_HEALTH_TEXT          1171
#define IDC_HAZARD_ATTACK_TEXT          1172
#define IDC_HAZARD_SPEED                1173
#define IDC_HAZARD_TURNRATE             1174
#define IDC_HAZARD_HEALTH               1175
#define IDC_HAZARD_ATTACK               1176
#define IDC_HAZARD_SPEED_SPIN           1177
#define IDC_HAZARD_TURNRATE_SPIN        1178
#define IDC_HAZARD_HEALTH_SPIN          1179
#define IDC_HAZARD_ATTACK_SPIN          1180
#define IDC_HAZARD_COLLISION            1181
#define IDC_HAZARD_RESPAWN_TEXT         1182
#define IDC_HAZARD_RESPAWN              1183
#define IDC_LAYERSHADE_GFX_CURRENT      1183
#define IDC_HAZARD_RESPAWN_SPIN         1184
#define IDC_LAYERSHADE_GFX_CURRENT_SPIN 1184
#define IDC_LAYERSHADE_GFX_LIST         1186
#define IDC_LAYERSHADE_GFX_GOTO         1190
#define IDC_LAYERSHADE_GFX_DELETE       1191
#define IDC_LAYERSHADE_GFX_X0           1192
#define IDC_LAYERSHADE_GFX_SPIN_X0      1193
#define IDC_LAYERSHADE_GFX_Y0           1194
#define IDC_LAYERSHADE_GFX_SPIN_Y0      1195
#define IDC_LAYERSHADE_GFX_X1           1196
#define IDC_LAYERSHADE_GFX_SPIN_X1      1197
#define IDC_LAYERSHADE_GFX_Y1           1198
#define IDC_LAYERSHADE_GFX_SPIN_Y1      1199
#define IDC_LAYERSHADE_GFX_X2           1200
#define IDC_LAYERSHADE_GFX_SPIN_X2      1201
#define IDC_LAYERSHADE_GFX_Y2           1202
#define IDC_LAYERSHADE_GFX_SPIN_Y2      1203
#define IDC_LAYERSHADE_GFX_X3           1204
#define IDC_LAYERSHADE_GFX_SPIN_X3      1205
#define IDC_LAYERSHADE_GFX_Y3           1206
#define IDC_LAYERSHADE_GFX_SPIN_Y3      1207
#define IDC_LAYERSHADE_GFX_TRANSLIST    1208
#define IDC_LAYERSHADE_GFX_X            1209
#define IDC_LAYERSHADE_GFX_XSPIN        1211
#define IDC_LAYERSHADE_GFX_Y            1212
#define IDC_LAYERSHADE_GFX_YSPIN        1213
#define IDC_LAYERSHADE_DEF_LIST         1214
#define IDC_LAYERSHADE_BRUSHTEXT        1215
#define IDC_LAYERSHADE_MODETEXT         1216
#define IDC_LAYERSHADE_MODELIST         1218
#define IDC_LAYERSHADE_BRUSHLIST        1219
#define IDC_LAYERSHADE_RATELIST         1220
#define IDC_LAYERSHADE_BIFILTER         1230
#define IDC_LAYERSHADE_TRIFILTER        1231
#define IDC_LAYERSHADE_SHADER           1232
#define IDC_LAYERSHADE_SHADERSPIN       1233
#define IDC_LAYERSHADE_SHADEG           1234
#define IDC_LAYERSHADE_SHADEGSPIN       1235
#define IDC_LAYERSHADE_SHADEB           1236
#define IDC_LAYERSHADE_SHADEBSPIN       1237
#define IDC_LAYERSHADE_SHADETEXT        1238
#define ID_TOOLBAR_TILEPALETTE          32774
#define ID_TOOLBAR_PARAMBAR             32783
#define ID_TOGGLE_SUBVIEW               32785
#define ID_MAP_TOGGLEGRID               32786
#define ID_TOGGLE_GRID                  32787
#define ID_MIRRORX                      32788
#define ID_MIRRORY                      32789
#define ID_ACTIVEBRUSH_LEFT             32790
#define ID_ACTIVEBRUSH_RIGHT            32791
#define ID_MAP_SETSIZE                  32792
#define ID_2D_3D_TOGGLE                 32794
#define ID_EXPORT                       32795
#define ID_ZOOM_IN                      32797
#define ID_ZOOM_OUT                     32798
#define ID_RESET_VIEW                   32799
#define ID_RENDER_TO_TGA                32800
#define ID_ROTATE                       32801
#define ID_REPORT                       32802
#define ID_INDICATOR_CURSORXY           59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1239
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
