#----------------------------------------------------------------------------
#	USER SPECEFIC MAKEFILE FOR art
#
#	Copyright (C) 1997 G R Liddon
#----------------------------------------------------------------------------


#	Obligatory Items
#	----------------


#STACK_SIZE := 6000

#	Set DEV_KIT to either SONY_ISA, SONY_PCI || CLIMAX
#	--------------------------------------------------

DEV_KIT :=     SONY_ISA


#	Set FILE_SYSTEM to CD || PC
#	CD reads files from CD (or the emulator)
#	PC reads files from the PC via dev kits back channel
#	----------------------------------------------------

FILE_SYSTEM	:=	PC


#	Set RAM_SIZE to a value in the range 2 - 8
#	------------------------------------------

RAM_SIZE        :=      2


#	Settings for Sony ISA dev kit
#	-----------------------------



#	Settings Sony PCI dev kit
#	-------------------------

SONY_ISA_ADDR		:= 1340
SONY_ISA_IRQ		:= 10


#	Settings for climax dev kit
#	---------------------------



#	Settings for visual C
#	If you want to compile Visual C stuff you need to set the following
#	MS_DIR var to point at where you've installed your stuff
#	for example:
#	-------------------------------------------------------------------

# MS_DIR :=	c:/program files/devstudio

FINAL_OVERLAYS := 1

#----------------------------------------------------------------------------
 #ends
